--liquibase formatted sql


--changeset vadym:1
CREATE TABLE events
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(250),
    image_url varchar(250),
    text text,
    date_time timestamp
);



