--liquibase formatted sql


--changeset vadym:1
CREATE TABLE confirmation_code
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code varchar NOT NULL UNIQUE,
    user_id int references users (user_id),
    date_time date
);



