package de.pet_project.domain;

public enum Genre {
        RPG, ARCADE, PUZZLE, CHILDREN_S_GAMES, INDIE,
        CASUAL, MUSICAL, ADVENTURES, SIMULATORS, SLOW_MO,
        SPORTS, SHOOTING, HORROR,SHOOTER, EXTREME, ACTION

}
